[package]
name = "shadcn-registry"
description = "Rust port of shadcn registry."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_with = "3.12.0"
